In [15]:
import torch
# Mengimpor library PyTorch untuk komputasi tensor dan autograd

x = torch.randn(3, requires_grad=True)
# Membuat tensor berukuran 3 dengan nilai acak dari distribusi normal (mean=0, std=1)
# requires_grad=True berarti PyTorch akan melacak semua operasi pada x

print(x)
# Menampilkan nilai tensor x

y = x + 2
# Operasi penjumlahan tensor x dengan konstanta 2
# Operasi ini dicatat dalam computation graph

print(y)
# Menampilkan hasil y

z = y * y * 2
# Menghitung z = 2 * (y^2) untuk setiap elemen
# Operasi ini juga dicatat dalam computation graph

print(z)
# Menampilkan nilai z (masih berupa tensor vektor)

# z = z.mean()
# (Jika diaktifkan) Mengubah z menjadi skalar dengan menghitung rata-rata
# Biasanya diperlukan agar backward() bisa dipanggil tanpa argumen

print(z)
# Menampilkan kembali z (masih vektor karena mean dikomentari)

v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
# Membuat tensor v sebagai gradien eksternal
# Digunakan saat backward pada tensor non-skalar

z.backward(v)
# Melakukan backpropagation
# v berfungsi sebagai gradien awal (∂L/∂z)
# Menghitung gradien z terhadap x

print(x.grad)
# Menampilkan gradien ∂z/∂x yang tersimpan di x.grad

tensor([-1.3331, -0.0201, -0.8109], requires_grad=True)
tensor([0.6669, 1.9799, 1.1891], grad_fn=<AddBackward0>)
tensor([0.8895, 7.8401, 2.8278], grad_fn=<MulBackward0>)
tensor([0.8895, 7.8401, 2.8278], grad_fn=<MulBackward0>)
tensor([2.6676e-01, 7.9197e+00, 4.7563e-03])


In [20]:
x = torch.rand(3, requires_grad=True)
# Membuat ulang tensor x baru dengan nilai acak uniform [0,1]
# requires_grad=True untuk pelacakan gradien

# x.requires_grad_(False)
# (Jika diaktifkan) Menonaktifkan pelacakan gradien pada x

print(x)
# Menampilkan nilai tensor x

# y = x.detach()
# detach() membuat tensor baru yang terlepas dari computation graph
# Gradien tidak akan mengalir kembali ke x

# print(y)
# Menampilkan tensor y hasil detach

with torch.no_grad():
  # Konteks ini menonaktifkan autograd sementara
  y = x + 2
  # Operasi ini tidak dicatat dalam computation graph
  print(y)
  # Menampilkan y tanpa melibatkan gradien

tensor([0.2704, 0.3450, 0.7644], requires_grad=True)
tensor([2.2704, 2.3450, 2.7644])


In [25]:
weights = torch.ones(4, requires_grad=True)
# Membuat tensor weights berisi 1 sebanyak 4 elemen
# Digunakan sebagai parameter (seperti bobot model)

for epoch in range(2):
  # Loop training sederhana selama 2 epoch

  model_output = (weights * 3).sum()
  # Operasi "model": setiap weight dikali 3 lalu dijumlahkan
  # Hasilnya adalah skalar

  model_output.backward()
  # Menghitung gradien model_output terhadap weights
  # Gradien akan terakumulasi di weights.grad

  print(weights.grad)
  # Menampilkan gradien weights setelah backward

  weights.grad.zero_()
  # Mengosongkan gradien
  # Penting karena PyTorch mengakumulasi gradien secara default

# RINGKASAN:
# Kode ini menjelaskan konsep inti autograd di PyTorch:
# - Cara PyTorch membangun computation graph secara otomatis
# - Backpropagation pada tensor skalar dan non-skalar
# - Peran gradien eksternal pada backward()
# - Penggunaan requires_grad, detach(), dan torch.no_grad()
# - Akumulasi gradien dan pentingnya reset gradien saat training model

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
