In [ ]:
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):
  def __init__(self, n_input_features):
    super(Model, self).__init__()
    # Memanggil constructor dari nn.Module

    self.linear = nn.Linear(n_input_features, 1)
    # Layer linear (fully connected)
    # - Input  : n_input_features (misalnya 6 fitur)
    # - Output : 1 neuron
    # Cocok untuk binary classification atau regresi

  def forward(self, x):
    # Fungsi forward: mendefinisikan alur data di model

    y_pred = torch.sigmoid(self.linear(x))
    # 1) x masuk ke linear layer → menghasilkan logits
    # 2) sigmoid mengubah logits menjadi nilai antara 0–1 (probabilitas)

    return y_pred
    # Mengembalikan prediksi akhir

model = Model(n_input_features = 6)
# Membuat instance model dengan 6 fitur input

# for param in model.parameters():
#   print(param)
# (Opsional) Menampilkan semua parameter model (weight & bias)

# FILE = '/content/model.pth'
# # torch.save(model, FILE)
# torch.save(model.state_dict(), FILE)
# Menyimpan parameter model saja (state_dict)
# Cara ini lebih fleksibel dan direkomendasikan

# # model = torch.load(FILE, weights_only=False)
# # model.eval()
# Contoh load model secara langsung (kurang direkomendasikan)

# loaded_model = Model(n_input_features=6)
# loaded_model.load_state_dict(torch.load(FILE))
# loaded_model.eval()
# Cara yang direkomendasikan:
# 1) Buat instance model
# 2) Load state_dict
# 3) Set ke mode evaluasi

# for param in model.parameters():
#   print(param)
# (Opsional) Cek ulang parameter setelah load


Parameter containing:
tensor([[-0.3750,  0.1141,  0.3260, -0.3970,  0.2900, -0.2225]],
       requires_grad=True)
Parameter containing:
tensor([-0.1485], requires_grad=True)
Parameter containing:
tensor([[-0.3750,  0.1141,  0.3260, -0.3970,  0.2900, -0.2225]],
       requires_grad=True)
Parameter containing:
tensor([-0.1485], requires_grad=True)


In [ ]:
learning_rate = 0.01
# Learning rate optimizer

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)
# Membuat optimizer SGD
# - Mengoptimasi parameter model
# - Learning rate = 0.01

print(optimizer.state_dict())
# Menampilkan state optimizer:
# - parameter groups
# - momentum (jika ada)
# - learning rate, dll

# checkpoint = {
#     'epoch': 90,
#     'model_state': model.state_dict(),
#     'optim_state': optimizer.state_dict()
# }
# Membuat checkpoint:
# - epoch terakhir
# - state model
# - state optimizer

# torch.save(checkpoint, 'checkpoint.pth')
# Menyimpan checkpoint ke file

loaded_checkpoint = torch.load('checkpoint.pth')
# Memuat checkpoint dari file

epoch = loaded_checkpoint['epoch']
# Mengambil informasi epoch terakhir training

model = Model(n_input_features=6)
# Membuat ulang model (arsitektur HARUS sama)

optimizer = torch.optim.SGD(model.parameters(), lr=0)
# Membuat optimizer baru
# Learning rate akan ditimpa oleh state_dict optimizer

model.load_state_dict(loaded_checkpoint['model_state'])
# Memuat parameter model dari checkpoint

optimizer.load_state_dict(loaded_checkpoint['optim_state'])
# Memuat state optimizer dari checkpoint
# (termasuk learning rate, momentum, dll)

print(optimizer.state_dict())
# Menampilkan state optimizer setelah load
# Menunjukkan bahwa optimizer berhasil direstore

{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}
{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}


In [ ]:
# 4. Checkpoint
#    - Checkpoint menyimpan:
#      a) epoch terakhir
#      b) parameter model
#      c) state optimizer
#    - Berguna untuk melanjutkan training dari titik terakhir
#
# 5. Loading Checkpoint
#    - Arsitektur model harus sama
#    - state_dict model dan optimizer di-restore
#    - Training bisa dilanjutkan tanpa kehilangan informasi
#
# Intinya:
# Code ini menunjukkan cara menyimpan dan memuat
# model + optimizer + epoch untuk training berkelanjutan.