In [ ]:
import torch
import torch.nn as nn
import numpy as np

In [ ]:
def softmax(x):
  return np.exp(x) / np.sum(np.exp(x), axis=0)
# Fungsi softmax manual menggunakan NumPy
# Mengubah nilai logits menjadi probabilitas
# Probabilitas total = 1

x = np.array([2.0, 1.0, 0.1])
# Contoh vektor logits (nilai mentah model)

outputs = softmax(x)
# Menghitung softmax secara manual

print('softmax numpy:', outputs)
# Menampilkan hasil softmax versi NumPy

softmax numpy: [0.65900114 0.24243297 0.09856589]


In [ ]:
x = torch.tensor([2.0, 1.0, 0.1])
# Logits yang sama tetapi dalam bentuk tensor PyTorch

outputs = torch.softmax(x, dim=0)
# Softmax bawaan PyTorch
# dim=0 → softmax dihitung sepanjang dimensi kelas

print(outputs)
# Menampilkan hasil softmax versi PyTorch

tensor([0.6590, 0.2424, 0.0986])


In [ ]:
def cross_entropy(actual, predicted):
  loss = -np.sum(actual * np.log(predicted))
  return loss
# Fungsi cross-entropy loss manual
# actual     → label one-hot
# predicted  → probabilitas hasil softmax

Y = np.array([1,0,0])
# Label one-hot
# Kelas benar adalah indeks 0

Y_pred_good = np.array([0.7, 0.2, 0.1])
# Prediksi yang cukup benar (probabilitas terbesar di kelas benar)

Y_pred_bad = np.array([0.1, 0.3, 0.6])
# Prediksi yang salah (kelas benar probabilitas kecil)

l1 = cross_entropy(Y, Y_pred_good)
# Loss untuk prediksi yang baik

l2 = cross_entropy(Y, Y_pred_bad)
# Loss untuk prediksi yang buruk

print(f'Loss1 numpy: {l1:.4f}')
print(f'Loss2 numpy: {l2:.4f}')
# Menampilkan loss:
# - Loss kecil → prediksi baik
# - Loss besar → prediksi buruk

Loss1 numpy: 0.3567
Loss2 numpy: 2.3026


In [ ]:
loss = nn.CrossEntropyLoss()
# CrossEntropyLoss bawaan PyTorch
# Sudah menggabungkan:
# - LogSoftmax
# - Negative Log Likelihood

Y = torch.tensor([2, 0, 1])
# Label target dalam bentuk class index (BUKAN one-hot)
# Setiap elemen menunjukkan kelas benar untuk tiap sample

# Y_pred_good = torch.tensor([[2.0, 1.0, 0.1]])
# Contoh logits satu sample (dikomentari)

# Y_pred_bad = torch.tensor([[0.5, 2.0, 0.3]])
# Contoh logits satu sample (dikomentari)

Y_pred_good = torch.tensor([
    [0.1, 1.0, 2.1],
    [2.0, 1.0, 0.1],
    [0.1, 3.0, 0.1]
])
# Logits prediksi yang relatif benar untuk 3 sample
# Nilai tertinggi sesuai dengan label di Y

Y_pred_bad = torch.tensor([
    [2.1, 1.0, 0.1],
    [0.1, 1.0, 2.1],
    [0.1, 3.0, 0.1]
])
# Logits prediksi yang relatif salah
# Beberapa nilai tertinggi tidak sesuai label

l1 = loss(Y_pred_good, Y)
# Menghitung loss untuk prediksi yang baik

l2 = loss(Y_pred_bad, Y)
# Menghitung loss untuk prediksi yang buruk

print(l1.item())
print(l2.item())
# Menampilkan nilai loss
# Loss prediksi baik lebih kecil dibanding prediksi buruk

_, predictions1 = torch.max(Y_pred_good, 1)
# Mengambil index kelas dengan nilai logits terbesar (prediksi kelas)

_, predictions2 = torch.max(Y_pred_bad, 1)
# Prediksi kelas untuk logits yang buruk

print(predictions1)
print(predictions2)
# Menampilkan hasil prediksi kelas
# Dibandingkan dengan Y untuk mengecek akurasi

0.3018244206905365
1.6241613626480103
tensor([2, 0, 1])
tensor([0, 2, 1])
